### ISSUE TITLE
error massege

### ISSUE THREAD

**Issue by topraktxrk** [Vinyzu/DiscordGenerator#101]
[ERROR] - Line 179  - generate_unclaimed() - Catched Exception, trying to save Token anyways...
 Error:
 Traceback (most recent call last):
  File "C:\Users\toprak\DISLOCK\main.py", line 99, in generate_unclaimed
    await self.page.type('[class *= "username"]', self.browser.faker.username)
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\botright\modules\playwright_mock\page.py", line 161, in type_mocker
    await Page.type(page, selector, text, delay=delay, no_wait_after=no_wait_after, strict=strict, timeout=timeout)
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\botright\modules\playwright_mock\page.py", line 309, in type
    element = await page.wait_for_selector(selector, state="visible", strict=strict, timeout=timeout)
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\botright\modules\playwright_mock\page.py", line 69, in mock_wait_for_selector
    element = await page._wait_for_selector(selector, state=state, strict=strict, timeout=timeout)
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 8235, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_page.py", line 368, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Users\toprak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[class *= \"username\"]") to be visible
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
  locator resolved to hidden <input value="" type="text" class="username-1XgXmI" pla…/>
============================================================

**Comment by Vinyzu** [comment]
First off, please dont put your error in the issue's title.

But ill look into it when ill continue support.
