### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'person'

### ISSUE THREAD

**Issue by ProtDos** [Vinyzu/DiscordGenerator#25]
```[INFO] - Line 199  - initialize() - Spawned Browser successfully
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\Tokengenerator\DiscordGenerator-main\main.py", line 707, in generate_token
    self.person.username+f"{random.randint(10, 99)}@gmail.com")
AttributeError: 'Generator' object has no attribute 'person'

[ERROR] - Line 789  - generate_token() - Catched Exception, trying to save Token anyways... 
 Error:
[INFO] - Line 199  - initialize() - Spawned Browser successfully
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\Tokengenerator\DiscordGenerator-main\main.py", line 707, in generate_token
    self.person.username+f"{random.randint(10, 99)}@gmail.com")
AttributeError: 'Generator' object has no attribute 'person'
```

**Comment by ProtDos** [comment]
I fixed it, thx anyway

**Comment by Vinyzu** [comment]
Can u pr?

**Comment by ProtDos** [comment]
I'll when I am home
