### ISSUE TITLE
ValueError: The number of derivatives at boundaries does not match: expected 1, got 0+0

### ISSUE THREAD

**Issue by adv-zl** [Vinyzu/DiscordGenerator#3]
Why this error occures?
```

captcha_solver() - [[674, 499], [637, 634]]
Traceback (most recent call last):
  File "/Volumes/NO NAME/nft_land/discord_project/DiscordGenerator-main/main.py", line 954, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Volumes/NO NAME/nft_land/discord_project/DiscordGenerator-main/main.py", line 949, in main
    await asyncio.gather(*threadz)
  File "/Volumes/NO NAME/nft_land/discord_project/DiscordGenerator-main/main.py", line 194, in initialize
    await self.generate_token()
  File "/Volumes/NO NAME/nft_land/discord_project/DiscordGenerator-main/main.py", line 673, in generate_token
    captcha = await self.captcha_solver()
  File "/Volumes/NO NAME/nft_land/discord_project/DiscordGenerator-main/main.py", line 448, in captcha_solver
    self.x_new, self.y_new = self.smooth_out_mouse()
  File "/Volumes/NO NAME/nft_land/discord_project/DiscordGenerator-main/main.py", line 335, in smooth_out_mouse
    f = scipy.interpolate.interp1d(x, y, kind='quadratic')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 532, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 826, in make_interp_spline
    raise ValueError("The number of derivatives at boundaries does not "
ValueError: The number of derivatives at boundaries does not match: expected 1, got 0+0
```

**Comment by Vinyzu** [comment]
Probably cause there just two captcha points, ill check later and update accordingly

**Comment by Vinyzu** [comment]
Fixxed in new Version v1.0.1
https://github.com/Vinyzu/DiscordGenerator/commit/cf7ba7827b4849f6e0b9a10b1e5a6f252fb59a14
