### ISSUE TITLE
Not joining servers

### ISSUE THREAD

**Issue by nerulek** [Vinyzu/DiscordGenerator#41]
shows invalid mail, prevents registration.
joining the server does not work ;c
[errorcode.txt](https://github.com/Vinyzu/DiscordGenerator/files/9454236/errorcode.txt)

**Comment by Vinyzu** [comment]
```
Traceback (most recent call last):
  File "C:\Users\nope\Desktop\DiscordGenerator-main\main.py", line 681, in generate_unclaimed
    await self.join_server()
  File "C:\Users\nope\Desktop\DiscordGenerator-main\main.py", line 970, in join_server
    await self.click_humanly("", '[class *= "footerButton-24QPis"]')
  File "C:\Users\nope\Desktop\DiscordGenerator-main\main.py", line 312, in click_humanly
    coordinates = await element.bounding_box(timeout=timeout)
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\async_api\_generated.py", line 12334, in bounding_box
    await self._impl_obj.bounding_box(timeout=timeout)
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_locator.py", line 116, in bounding_box
    return await self._with_element(
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_locator.py", line 100, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_locator.py", line 220, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 387, in wrap_api_call
    return await cb()
  File "C:\Users\nope\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[class *= "footerButton-24QPis"]"
=========================== logs ===========================
```

**Comment by FuckingToasters** [comment]
bump

**Comment by Vinyzu** [comment]
Should be fixxed in newest version v2.0: https://github.com/Vinyzu/DiscordGenerator/commit/756939fa6a02453a54691ec398971f1f8f67eacf
