### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by LIL-JABA** [Vinyzu/DiscordGenerator#52]
Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\DiscordGenerator-main\main.py", line 1129, in <module>
    asyncio.run(main())
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\MrBebra\Desktop\DiscordGenerator-main\main.py", line 1124, in main
    await asyncio.gather(*threadz)
  File "C:\Users\MrBebra\Desktop\DiscordGenerator-main\main.py", line 204, in initialize
    await self.initialize_browser()
  File "C:\Users\MrBebra\Desktop\DiscordGenerator-main\main.py", line 229, in initialize_browser
    main_browser = await self.playwright.firefox.launch(args=["incognito"], headless=False, proxy=self.browser_proxy if self.proxy else None)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_generated.py", line 11650, in launch
    await self._impl_obj.launch(
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 387, in wrap_api_call
    return await cb()
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\MrBebra\AppData\Local\ms-playwright\firefox-1344\firefox\firefox.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000002C848083880>
Traceback (most recent call last):
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closedRuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002C8480A1360>
Traceback (most recent call last):
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closedRuntimeError: Event loop is closed

**Comment by Vinyzu** [comment]
Read The Error Mate.
`playwraight install`
and ur good
