### ISSUE TITLE
cant run script botright error 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [Vinyzu/DiscordGenerator#69]
hi i cant run script pls help 
error code : 
C:\Users\ssdf\Desktop\DiscordGenerator-main>python main.py
Traceback (most recent call last):
  File "C:\Users\ssdf\Desktop\DiscordGenerator-main\main.py", line 9, in <module>
    import botright
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\__init__.py", line 3, in <module>
    from .botright import *
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\botright.py", line 6, in <module>
    from .modules.playwright_mock import browser
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\playwright_mock\__init__.py", line 7, in <module>
    from .page import new_page
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\playwright_mock\page.py", line 7, in <module>
    from .. import hcaptcha
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha.py", line 8, in <module>
    from .hcaptcha_challenger import (DIR_CHALLENGE, DIR_MODEL, PATH_OBJECTS_YAML, ArmorCaptcha)
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha_challenger\__init__.py", line 6, in <module>
    from .core import ArmorCaptcha
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha_challenger\core.py", line 4, in <module>
    from .solutions import resnet, sk_recognition, yolo
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha_challenger\solutions\resnet.py", line 16, in <module>
    from .kernel import ChallengeStyle
  File "C:\Users\ssdf\AppData\Local\Programs\Python\Python39\lib\site-packages\botright\modules\hcaptcha_challenger\solutions\kernel.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by TurfuFrogy** [comment]
`pip install requests`
