### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by ThePrivatePanda** [Vinyzu/DiscordGenerator#72]
## Reproduction Steps.
- Launch the generator.
- Attempt to create a non-claimed non-verfied humanized token.
- No extra/optional params used.

## Flow.
Everything proceeds smoothly, somewhy though, goes into user settings and times out while attempting to click something- I'm not sure what it's supposed to do.

### Error:
waiting for selector "[class *= "item-3XjbnG"] >> nth=6" to be visible

### Traceback:
[ERROR] - Line 179  - generate_unclaimed() - Catched Exception, trying to save Token anyways... 
 Error:
 Traceback (most recent call last):
  File "D:\venv\DISLOCK\main.py", line 162, in generate_unclaimed
    await Discord.humanize_token(self)
  File "D:\venv\DISLOCK\modules\discord.py", line 56, in humanize_token
    await profile_button.click()
  File "D:\venv\DISLOCK\.venv\lib\site-packages\botright\modules\playwright_mock\locator.py", line 19, in click_mocker
    await Locator.click(locator, button=button, click_count=click_count, delay=delay, force=force, modifiers=modifiers, no_wait_after=no_wait_after, position=position, timeout=timeout, trial=trial)       
  File "D:\venv\DISLOCK\.venv\lib\site-packages\botright\modules\playwright_mock\locator.py", line 99, in click
    await locator.wait_for(state="visible", timeout=timeout)
  File "D:\venv\DISLOCK\.venv\lib\site-packages\playwright\async_api\_generated.py", line 13757, in wait_for
    await self._impl_obj.wait_for(timeout=timeout, state=state)
  File "D:\venv\DISLOCK\.venv\lib\site-packages\playwright\_impl\_locator.py", line 522, in wait_for
    await self._frame.wait_for_selector(
  File "D:\venv\DISLOCK\.venv\lib\site-packages\playwright\_impl\_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "D:\venv\DISLOCK\.venv\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "D:\venv\DISLOCK\.venv\lib\site-packages\playwright\_impl\_connection.py", line 387, in wrap_api_call
    return await cb()
  File "D:\venv\DISLOCK\.venv\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.

### Repetition.
Error is repetitive under same circumstances.

### Major
Does NOT close the window after the error; I'm not sure if this is expected behaviour or not, but I'd rather not have 69 windows floating about.

## Environment
- Windows 11 x86
- python v3.10.5
- Essential libraries installed inside a python virtual environment

**Comment by FuckingToasters** [comment]
#84
