### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by jprocks101** [Vinyzu/DiscordGenerator#79]
Traceback (most recent call last):
  File "C:\Users\=\Downloads\DiscordGenerator-main (1)\DiscordGenerator-main\main.py", line 219, in generate_token
    await self.page.solve_hcaptcha()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\playwright_mock\page.py", line 334, in solve_mocker
    return await hcaptcha.hCaptcha.solve_hcaptcha(page, rqdata=rqdata)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 189, in solve_hcaptcha
    return await hCaptcha.solve_captcha(page, checkbox)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\botright\modules\hcaptcha.py", line 102, in solve_captcha
    image_url = style.split('url("')[1].split('"')[0]
IndexError: list index out of range

**Comment by Vinyzu** [comment]
Open Issue on Botright
