### ISSUE TITLE
JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.

### ISSUE THREAD

**Issue by Abelkrijgtalles** [Vinyzu/DiscordGenerator#87]
If I run the program I get the error:
`JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.`
This is the full log (including options):
`C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\Scripts\python.exe C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\main.py 
Executing <Task pending name='Task-2' coro=<Botright.__ainit__() running at C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\botright\botright.py:18> wait_for=<Future pending cb=[Task.task_wakeup()] created at C:\Users\abelv\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:429> cb=[WeakSet.remove(), Task.task_wakeup()] created at C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\async_class.py:36> took 1.703 seconds
Executing <Task pending name='Task-5' coro=<Connection.run.<locals>.init() running at C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_connection.py:222> wait_for=<Future pending cb=[Task.task_wakeup()] created at C:\Users\abelv\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:429> cb=[ProtocolCallback.__init__.<locals>.cb() at C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_connection.py:145] created at C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_connection.py:225> took 1.172 seconds
 _____     __     ______     __         ______     ______     __  __
/\  __-.  /\ \   /\  ___\   /\ \       /\  __ \   /\  ___\   /\ \/ /
\ \ \/\ \ \ \ \  \ \___  \  \ \ \____  \ \ \/\ \  \ \ \____  \ \  _"-.
 \ \____-  \ \_\  \/\_____\  \ \_____\  \ \_____\  \ \_____\  \ \_\ \_\
  \/____/   \/_/   \/_____/   \/_____/   \/_____/   \/_____/   \/_/\/_/    | Made by Vinyzu
                                                                           | https://github.com/Vinyzu/DiscordGenerator
[Select] - [Generation Mode]
<1> Generate Unclaimed Token
<2> Generate Token
<3> Test Captcha
</> 2
[Select] - [Email Verification]
<1> Verification Enabled
<2> No Verification
</> 1
[Select] - [Token Humanization]
<1> Humanization Enabled
<2> No Humanization
</> 1
[Input] - [Threads Amount]
</> 1
[Drag&Drop] - [Proxy File]
<?> Or Leave empty for Proxyless Mode
</> 
[Drag&Drop] - [Output File]
<?> Or Leave empty to use output.txt
</> 
[Input] - [Invite Link]
<?> Either parse a InviteLink, or an InviteCode
</> 
[Input] - [Output Format]
<?> Token: token, Email: email, Password: pass, Proxy: proxy
<?> Leave empty for standart output: token:email:pass
</> 
Executing <Task pending name='Task-1' coro=<main() running at C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\main.py:400> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at C:\Users\abelv\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py:665> cb=[_run_until_complete_cb() at C:\Users\abelv\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:184] created at C:\Users\abelv\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py:636> took 11.469 seconds
[INFO] - Line 31  - initialize() - Spawned Browser successfully
Traceback (most recent call last):
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\main.py", line 400, in main
    await asyncio.gather(*threadz)
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\main.py", line 33, in initialize
    self.page = await self.browser.new_page()
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\botright\modules\playwright_mock\browser.py", line 35, in page_mocker
    return await page.new_page(botright, browser, proxy, faker, **launch_arguments)
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\botright\modules\playwright_mock\page.py", line 11, in new_page
    page = await browser._new_page(**launch_arguments)
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\async_api\_generated.py", line 10250, in new_page
    return mapping.from_impl(await self._impl_obj.new_page())
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_browser_context.py", line 228, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_connection.py", line 387, in wrap_api_call
    return await cb()
  File "C:\Users\abelv\OneDrive\Documenten\Programmeren\Go\DISLOCK\venv\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.newPage): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\abelv\AppData\Local\ms-playwright\firefox-1344\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\abelv\AppData\Local\Temp\playwright_firefoxdev_profile-ihWCvl -juggler-pipe -silent
<launched> pid=15924
[pid=15924][out] 
[pid=15924][out] Juggler listening to the pipe
[pid=15924][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 68: Error: Can't find profile directory.

Process finished with exit code 0`

These are my packages:
`botright==0.1.3
httpx~=0.23.0
validators~=0.20.0`

**Comment by Abelkrijgtalles** [comment]
I know that it's kinda buggy, but i can't fix it
